// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCEuGny-MhZ4ApnF_9EpkFfiSzmJnH70',
    appId: '1:373499961527:web:eaebb7b70df4e801b92d32',
    messagingSenderId: '373499961527',
    projectId: 'bluetooth-chat-app-3d235',
    authDomain: 'bluetooth-chat-app-3d235.firebaseapp.com',
    storageBucket: 'bluetooth-chat-app-3d235.appspot.com',
    measurementId: 'G-MS485T8SY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBENfsvPXlOKFyW2HNnfSMOw4oGt2x0AyY',
    appId: '1:373499961527:android:5f6a24c4aa6b8053b92d32',
    messagingSenderId: '373499961527',
    projectId: 'bluetooth-chat-app-3d235',
    storageBucket: 'bluetooth-chat-app-3d235.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMcSjVCoB62zDVlU3CqIcGTE4_Arnbdg',
    appId: '1:373499961527:ios:3dd4b83c8719659cb92d32',
    messagingSenderId: '373499961527',
    projectId: 'bluetooth-chat-app-3d235',
    storageBucket: 'bluetooth-chat-app-3d235.appspot.com',
    iosBundleId: 'com.example.bluetoothBasedChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMcSjVCoB62zDVlU3CqIcGTE4_Arnbdg',
    appId: '1:373499961527:ios:3dd4b83c8719659cb92d32',
    messagingSenderId: '373499961527',
    projectId: 'bluetooth-chat-app-3d235',
    storageBucket: 'bluetooth-chat-app-3d235.appspot.com',
    iosBundleId: 'com.example.bluetoothBasedChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCEuGny-MhZ4ApnF_9EpkFfiSzmJnH70',
    appId: '1:373499961527:web:4ab7d4fe5520b868b92d32',
    messagingSenderId: '373499961527',
    projectId: 'bluetooth-chat-app-3d235',
    authDomain: 'bluetooth-chat-app-3d235.firebaseapp.com',
    storageBucket: 'bluetooth-chat-app-3d235.appspot.com',
    measurementId: 'G-E3MJB8Z4Q8',
  );
}
